### ISSUE TITLE
bus: signatures need to be properly parsed when generating introspection xml.

### ISSUE THREAD

**Issue by mvollmer** [allisonkarlitskaya/systemd_ctypes#32]
https://github.com/allisonkarlitskaya/systemd_ctypes/blob/1833c33b3846c974f0f8146023479f3d69e7746d/systemd_ctypes/bus.py#L359

I think this is incorrect.  It works for 'ss' -> [ 's', 's' ] but not for more complex signatures, like `a(ss)`, no?

**Comment by allisonkarlitskaya** [comment]
Sorry for not responding to this before.  This is not a bug.  If you want to specify more complex types, you need to give them as a sequence.  `'ss'` is indeed only a shortcut when all of the types are single character (since iterating `'ss'` gives `['s', 's']`).
