### ISSUE TITLE
feat: show os.stat information for files and directories in 'created' events

### ISSUE THREAD

**Issue by KKoukiou** [allisonkarlitskaya/systemd_ctypes#56]

**Comment by allisonkarlitskaya** [comment]
I think this is out of scope for the PathWatch API, but one thing we could do to make it easier to implement the requested feature is to pass our copy of the `Handle` on all events, not just identity changes.

You'd probably also want to check for (and report) changes on `IN_ATTRIB`.

That would make it trivial to call `fstat()` or `stat(dirfd=)` from the handler.

With the existing API it's still possible — you just need to keep track of the fd for yourself, which is a bit annoying.

**Comment by allisonkarlitskaya** [comment]
This isn't how we're going to get info to cockpit-navigator.  Closing this.  See cockpit-project/cockpit#19845
